# Generated by Django 6.0.6 on 2026-06-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioanalysis',
            name='beats',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='audioanalysis',
            name='file',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
