# Generated by Django 6.0.6 on 2026-06-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_audioanalysis_beats_alter_audioanalysis_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioanalysis',
            name='original_filename',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
